//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.CTMS.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_DRUGUSE
    {
        public decimal ID { get; set; }
        public string DISEASEID { get; set; }
        public string USERID { get; set; }
        public string DRUGTYPE { get; set; }
        public string DRUGNAME { get; set; }
        public string DRUGID { get; set; }
        public string TREATMENTDISEASES { get; set; }
        public Nullable<System.DateTime> STARTTIME { get; set; }
        public Nullable<System.DateTime> ENDTIME { get; set; }
        public string TIMESADAY { get; set; }
        public string DOSE { get; set; }
        public string UNITS { get; set; }
        public Nullable<decimal> USEDAY { get; set; }
        public string ISNEWDRUG { get; set; }
        public string CREATEUSERID { get; set; }
        public Nullable<System.DateTime> CREATEDATETIME { get; set; }
        public string EDITUSERID { get; set; }
        public Nullable<System.DateTime> EDITDATETIME { get; set; }
        public string ISDELETED { get; set; }
        public string OWNERID { get; set; }
    }
}
