//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.CTMS.DAL.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CRDatabase : DbContext
    {
        public CRDatabase()
            : base("name=CRDatabase")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CR_DRUGEFFECT> CR_DRUGEFFECT { get; set; }
        public DbSet<CR_DRUGUSE> CR_DRUGUSE { get; set; }
        public DbSet<CR_GENEEFFECT> CR_GENEEFFECT { get; set; }
        public DbSet<CR_HABITS> CR_HABITS { get; set; }
        public DbSet<CTMS_ACCOUNTRECORD> CTMS_ACCOUNTRECORD { get; set; }
        public DbSet<CTMS_ADM_EXAMINEITEMOPTIONS> CTMS_ADM_EXAMINEITEMOPTIONS { get; set; }
        public DbSet<CTMS_ADM_EXAMINEITEMS> CTMS_ADM_EXAMINEITEMS { get; set; }
        public DbSet<CTMS_ADM_EXAMINETEMPLATES> CTMS_ADM_EXAMINETEMPLATES { get; set; }
        public DbSet<CTMS_BASETEMPLATERESULT> CTMS_BASETEMPLATERESULT { get; set; }
        public DbSet<CTMS_CONDITIONITEM> CTMS_CONDITIONITEM { get; set; }
        public DbSet<CTMS_EVENTPRODUCT> CTMS_EVENTPRODUCT { get; set; }
        public DbSet<CTMS_GUIDELINE> CTMS_GUIDELINE { get; set; }
        public DbSet<CTMS_GUIDELINEDATA> CTMS_GUIDELINEDATA { get; set; }
        public DbSet<CTMS_GUIDELINEFLOW> CTMS_GUIDELINEFLOW { get; set; }
        public DbSet<CTMS_GUIDELINEPRODUCT> CTMS_GUIDELINEPRODUCT { get; set; }
        public DbSet<CTMS_IMAGEEXAMINEREPORT> CTMS_IMAGEEXAMINEREPORT { get; set; }
        public DbSet<CTMS_IMAGEEXAMINEREPORTDETAIL> CTMS_IMAGEEXAMINEREPORTDETAIL { get; set; }
        public DbSet<CTMS_MEMBER> CTMS_MEMBER { get; set; }
        public DbSet<CTMS_MEMBERPRODUCTS> CTMS_MEMBERPRODUCTS { get; set; }
        public DbSet<CTMS_METADATA> CTMS_METADATA { get; set; }
        public DbSet<CTMS_METADATAPARAM> CTMS_METADATAPARAM { get; set; }
        public DbSet<CTMS_MYHOUSEKEEPER> CTMS_MYHOUSEKEEPER { get; set; }
        public DbSet<CTMS_MYPRODUCT> CTMS_MYPRODUCT { get; set; }
        public DbSet<CTMS_MYQUESTION> CTMS_MYQUESTION { get; set; }
        public DbSet<CTMS_PARENTGUIDELINE> CTMS_PARENTGUIDELINE { get; set; }
        public DbSet<CTMS_PRODUCTS> CTMS_PRODUCTS { get; set; }
        public DbSet<CTMS_QA_TESTPAPER> CTMS_QA_TESTPAPER { get; set; }
        public DbSet<CTMS_QA_TESTPAPERANALYSIS> CTMS_QA_TESTPAPERANALYSIS { get; set; }
        public DbSet<CTMS_QA_TESTPAPERCHAPTER> CTMS_QA_TESTPAPERCHAPTER { get; set; }
        public DbSet<CTMS_QA_TESTPAPERFAVORITESITEM> CTMS_QA_TESTPAPERFAVORITESITEM { get; set; }
        public DbSet<CTMS_QA_TESTPAPERITEM> CTMS_QA_TESTPAPERITEM { get; set; }
        public DbSet<CTMS_QA_TESTPAPERITEMDB> CTMS_QA_TESTPAPERITEMDB { get; set; }
        public DbSet<CTMS_QA_TESTPAPERITEMOPTION> CTMS_QA_TESTPAPERITEMOPTION { get; set; }
        public DbSet<CTMS_QA_TESTPAPEROPTIONDB> CTMS_QA_TESTPAPEROPTIONDB { get; set; }
        public DbSet<CTMS_QA_TESTPAPERRESULANALYSIS> CTMS_QA_TESTPAPERRESULANALYSIS { get; set; }
        public DbSet<CTMS_QA_TESTPAPERRESULCHAPTER> CTMS_QA_TESTPAPERRESULCHAPTER { get; set; }
        public DbSet<CTMS_QA_TESTPAPERRESULDETAILS> CTMS_QA_TESTPAPERRESULDETAILS { get; set; }
        public DbSet<CTMS_QA_TESTPAPERRESULERROR> CTMS_QA_TESTPAPERRESULERROR { get; set; }
        public DbSet<CTMS_QA_TESTPAPERRESULT> CTMS_QA_TESTPAPERRESULT { get; set; }
        public DbSet<CTMS_QA_TESTPAPERRESUOPTION> CTMS_QA_TESTPAPERRESUOPTION { get; set; }
        public DbSet<CTMS_QA_TESTPAPERUSERFEEDBACK> CTMS_QA_TESTPAPERUSERFEEDBACK { get; set; }
        public DbSet<CTMS_QA_TESTSOLUTION> CTMS_QA_TESTSOLUTION { get; set; }
        public DbSet<CTMS_QA_TESTSOLUTIONGROUP> CTMS_QA_TESTSOLUTIONGROUP { get; set; }
        public DbSet<CTMS_SERVICETRACEINFO> CTMS_SERVICETRACEINFO { get; set; }
        public DbSet<CTMS_SYMPTOM> CTMS_SYMPTOM { get; set; }
        public DbSet<CTMS_SYMPTOMRECORDS> CTMS_SYMPTOMRECORDS { get; set; }
        public DbSet<CTMS_SYS_FUNCTION> CTMS_SYS_FUNCTION { get; set; }
        public DbSet<CTMS_SYS_FUNCTIONPERMISSION> CTMS_SYS_FUNCTIONPERMISSION { get; set; }
        public DbSet<CTMS_SYS_PERMISSION> CTMS_SYS_PERMISSION { get; set; }
        public DbSet<CTMS_SYS_ROLE> CTMS_SYS_ROLE { get; set; }
        public DbSet<CTMS_SYS_ROLEFUNCTION> CTMS_SYS_ROLEFUNCTION { get; set; }
        public DbSet<CTMS_SYS_USERINFO> CTMS_SYS_USERINFO { get; set; }
        public DbSet<CTMS_SYS_USERROLE> CTMS_SYS_USERROLE { get; set; }
        public DbSet<CTMS_SYS_USERTYPEROLES> CTMS_SYS_USERTYPEROLES { get; set; }
        public DbSet<CTMS_USERAPPLY> CTMS_USERAPPLY { get; set; }
        public DbSet<CTMS_USEREVENT> CTMS_USEREVENT { get; set; }
        public DbSet<DUG_CNDRUG> DUG_CNDRUG { get; set; }
        public DbSet<DUG_DRUG> DUG_DRUG { get; set; }
        public DbSet<DUG_DRUGINTERACTIONS> DUG_DRUGINTERACTIONS { get; set; }
        public DbSet<DUG_DRUGSYNONYMS> DUG_DRUGSYNONYMS { get; set; }
        public DbSet<DUG_ENZYMEPO> DUG_ENZYMEPO { get; set; }
        public DbSet<DUG_ENZYMES> DUG_ENZYMES { get; set; }
        public DbSet<DUG_ENZYMESACTIONS> DUG_ENZYMESACTIONS { get; set; }
        public DbSet<DUG_ENZYMESIDENTIFIER> DUG_ENZYMESIDENTIFIER { get; set; }
        public DbSet<DUG_ENZYMESSYNONYMS> DUG_ENZYMESSYNONYMS { get; set; }
        public DbSet<DUG_EXTERNALIDENTIFIERS> DUG_EXTERNALIDENTIFIERS { get; set; }
        public DbSet<DUG_PRODUCTS> DUG_PRODUCTS { get; set; }
        public DbSet<DUG_TARGETACTIONS> DUG_TARGETACTIONS { get; set; }
        public DbSet<DUG_TARGETIDENTIFIER> DUG_TARGETIDENTIFIER { get; set; }
        public DbSet<DUG_TARGETS> DUG_TARGETS { get; set; }
        public DbSet<DUG_TARGETSPO> DUG_TARGETSPO { get; set; }
        public DbSet<DUG_TRANSPORTERACTIONS> DUG_TRANSPORTERACTIONS { get; set; }
        public DbSet<DUG_TRANSPORTERIDENTIFIER> DUG_TRANSPORTERIDENTIFIER { get; set; }
        public DbSet<DUG_TRANSPORTERS> DUG_TRANSPORTERS { get; set; }
        public DbSet<DUG_TRANSPORTERSPO> DUG_TRANSPORTERSPO { get; set; }
        public DbSet<GN_DRUGALLELE> GN_DRUGALLELE { get; set; }
        public DbSet<GN_GENE> GN_GENE { get; set; }
        public DbSet<GN_GENEALLELE> GN_GENEALLELE { get; set; }
        public DbSet<GN_GENEALLELELOCUS> GN_GENEALLELELOCUS { get; set; }
        public DbSet<HPN_RESULTDESC> HPN_RESULTDESC { get; set; }
        public DbSet<HPN_SENDVERCODELOG> HPN_SENDVERCODELOG { get; set; }
        public DbSet<HPN_TEMPLATE> HPN_TEMPLATE { get; set; }
        public DbSet<HPN_TEMPLATEITEM> HPN_TEMPLATEITEM { get; set; }
        public DbSet<HPN_TEMPLATEITEMOPTIONS> HPN_TEMPLATEITEMOPTIONS { get; set; }
        public DbSet<HPN_TESTRESULT> HPN_TESTRESULT { get; set; }
        public DbSet<HPN_TESTRESULTDETAILS> HPN_TESTRESULTDETAILS { get; set; }
        public DbSet<HR_ACTIVITYLOG> HR_ACTIVITYLOG { get; set; }
        public DbSet<HR_ANNUALINCOME> HR_ANNUALINCOME { get; set; }
        public DbSet<HR_AREA> HR_AREA { get; set; }
        public DbSet<HR_ATTACHMENT> HR_ATTACHMENT { get; set; }
        public DbSet<HR_CNR_USER> HR_CNR_USER { get; set; }
        public DbSet<HR_DICTIONARY> HR_DICTIONARY { get; set; }
        public DbSet<HR_DISEASE> HR_DISEASE { get; set; }
        public DbSet<HR_DISEASECATEGORY> HR_DISEASECATEGORY { get; set; }
        public DbSet<HR_DISEASEHISTORY> HR_DISEASEHISTORY { get; set; }
        public DbSet<HR_EXAMINEITEMLABDETAIL> HR_EXAMINEITEMLABDETAIL { get; set; }
        public DbSet<HR_EXAMINEITEMS> HR_EXAMINEITEMS { get; set; }
        public DbSet<HR_EXAMINERECORD> HR_EXAMINERECORD { get; set; }
        public DbSet<HR_EXAMINERESULT> HR_EXAMINERESULT { get; set; }
        public DbSet<HR_EXAMINETEMPLATE> HR_EXAMINETEMPLATE { get; set; }
        public DbSet<HR_EXAMINETEMPLATES_DEL> HR_EXAMINETEMPLATES_DEL { get; set; }
        public DbSet<HR_FD_DISEASE> HR_FD_DISEASE { get; set; }
        public DbSet<HR_FD_MEMBER> HR_FD_MEMBER { get; set; }
        public DbSet<HR_FD_RELATION> HR_FD_RELATION { get; set; }
        public DbSet<HR_FILEUPLOAD> HR_FILEUPLOAD { get; set; }
        public DbSet<HR_IMAGEEXAMINATION> HR_IMAGEEXAMINATION { get; set; }
        public DbSet<HR_ITEMSTANDVAL> HR_ITEMSTANDVAL { get; set; }
        public DbSet<HR_LABORATORYRESULT> HR_LABORATORYRESULT { get; set; }
        public DbSet<HR_LABORATORYTESTITEM> HR_LABORATORYTESTITEM { get; set; }
        public DbSet<HR_LABTESTRECORD> HR_LABTESTRECORD { get; set; }
        public DbSet<HR_LABTESTRESULT> HR_LABTESTRESULT { get; set; }
        public DbSet<HR_PERSONDRUGHISTORY> HR_PERSONDRUGHISTORY { get; set; }
        public DbSet<HR_PERSONHEALTHHISTORY> HR_PERSONHEALTHHISTORY { get; set; }
        public DbSet<HR_PERSONINFO> HR_PERSONINFO { get; set; }
        public DbSet<HR_REF_CODEFILE> HR_REF_CODEFILE { get; set; }
        public DbSet<HR_SCORE> HR_SCORE { get; set; }
        public DbSet<HR_SCORETEMPLATE> HR_SCORETEMPLATE { get; set; }
        public DbSet<HR_SEEDOCHISICD> HR_SEEDOCHISICD { get; set; }
        public DbSet<HR_SEEDOCTORHISTORY> HR_SEEDOCTORHISTORY { get; set; }
        public DbSet<HR_TEMPLATEITEM> HR_TEMPLATEITEM { get; set; }
        public DbSet<HR_TEMPLATEITEMUNIT> HR_TEMPLATEITEMUNIT { get; set; }
        public DbSet<HR_TREATMENTHISTORY> HR_TREATMENTHISTORY { get; set; }
        public DbSet<HR_USERGENE> HR_USERGENE { get; set; }
        public DbSet<CTMS_INFO_LOGINFO> CTMS_INFO_LOGINFO { get; set; }
        public DbSet<CTMS_SYS_LOGINFO> CTMS_SYS_LOGINFO { get; set; }
        public DbSet<CTMS_SYS_RESETPASSWORDLOG> CTMS_SYS_RESETPASSWORDLOG { get; set; }
        public DbSet<HR_CNR_USER_BAK> HR_CNR_USER_BAK { get; set; }
        public DbSet<HR_EXAMINECATEGORY> HR_EXAMINECATEGORY { get; set; }
        public DbSet<HR_EXAMINEITEMCATEGORY> HR_EXAMINEITEMCATEGORY { get; set; }
        public DbSet<HR_LABTESTITEM> HR_LABTESTITEM { get; set; }
    }
}
