//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.CTMS.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTMS_QA_TESTPAPERRESULT
    {
        public string RESULTID { get; set; }
        public string TESTPAPERID { get; set; }
        public string TESTPAPERCODE { get; set; }
        public string TESTPAPERNAME { get; set; }
        public string DISEASECODE { get; set; }
        public string DISEASENAME { get; set; }
        public string TESTPAPERSOURCE { get; set; }
        public Nullable<float> TOTOLSCORE { get; set; }
        public string TESTPAPERDESCRIPTION { get; set; }
        public Nullable<System.DateTime> TESTDATE { get; set; }
        public string USERID { get; set; }
        public decimal TESTSTATUS { get; set; }
        public string TESTIP { get; set; }
        public Nullable<float> TESTSCORE { get; set; }
        public string TESTRESULT { get; set; }
        public string RESULTDETAIL { get; set; }
    }
}
