//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.CTMS.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTMS_CONDITIONITEM
    {
        public decimal ID { get; set; }
        public decimal CONDTYPE { get; set; }
        public string DISPLAYNAME { get; set; }
        public decimal DATATYPE { get; set; }
        public string CATEGORY { get; set; }
        public Nullable<decimal> METADATAID { get; set; }
        public decimal OPERATOR { get; set; }
        public string OPERATEVALUE { get; set; }
        public decimal LOGICALOPERATOR { get; set; }
        public string CONDIDS { get; set; }
        public string CREATEUSERID { get; set; }
        public string CREATEUSERNAME { get; set; }
        public Nullable<System.DateTime> CREATEDATETIME { get; set; }
        public string EDITUSERID { get; set; }
        public string EDITUSERNAME { get; set; }
        public Nullable<System.DateTime> EDITDATETIME { get; set; }
        public string OWNERID { get; set; }
        public string OWNERNAME { get; set; }
        public decimal ISDELETED { get; set; }
    }
}
