//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.CTMS.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTMS_IMAGEEXAMINEREPORT
    {
        public string ID { get; set; }
        public string TEMPLATETYPE { get; set; }
        public Nullable<System.DateTime> CHECKDATE { get; set; }
        public string DEPT { get; set; }
        public string PART { get; set; }
        public string DIAGNOSE { get; set; }
        public string SEE { get; set; }
        public Nullable<System.DateTime> CREATEDATETIME { get; set; }
        public string CREATEUSERID { get; set; }
        public string CREATEUSERNAME { get; set; }
        public Nullable<System.DateTime> EDITDATETIME { get; set; }
        public string EDITUSERID { get; set; }
        public string EDITUSERNAME { get; set; }
        public Nullable<decimal> ISDELETED { get; set; }
        public string REPORTDOCTOR { get; set; }
        public string CHECKDOCTOR { get; set; }
        public byte[] REPORTDETAIL { get; set; }
        public string REMARK { get; set; }
        public string USERID { get; set; }
    }
}
