//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.CTMS.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTMS_GUIDELINEPRODUCT
    {
        public string GUIDELINEPRODUCTID { get; set; }
        public string GUIDELINEID { get; set; }
        public string PRODUCTID { get; set; }
        public string PRODUCTNAME { get; set; }
        public Nullable<float> PRODUCTPRICE { get; set; }
        public string PRODUCTDES { get; set; }
        public string ISALREADYBUY { get; set; }
    }
}
