//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.CTMS.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTMS_USEREVENT
    {
        public string EVENTID { get; set; }
        public string USERAPPLYID { get; set; }
        public string ACTIONTYPE { get; set; }
        public string ACTIONINFO { get; set; }
        public Nullable<System.DateTime> RECEIPTTIME { get; set; }
        public Nullable<System.DateTime> ENDTIME { get; set; }
        public string ACTIONSTATUS { get; set; }
        public string FROMUSER { get; set; }
        public string TOUSER { get; set; }
        public string TOUSERTYPE { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string MODELTYPE { get; set; }
        public string MODELID { get; set; }
        public string REMARKS { get; set; }
        public string LINKURL { get; set; }
    }
}
