//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.CTMS.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTMS_USERAPPLY
    {
        public string ID { get; set; }
        public string APPLYID { get; set; }
        public string USERID { get; set; }
        public string GUIDELINEID { get; set; }
        public string CURRENTNODE { get; set; }
        public string STATUS { get; set; }
        public string DOCTORSUGGEST { get; set; }
        public Nullable<System.DateTime> ENTRYDATE { get; set; }
        public Nullable<System.DateTime> EXITDATE { get; set; }
        public string CREATEUSERID { get; set; }
        public Nullable<System.DateTime> CREATEDATETIME { get; set; }
        public string EDITUSERID { get; set; }
        public Nullable<System.DateTime> EDITDATETIME { get; set; }
        public Nullable<decimal> ISDELETED { get; set; }
        public string OWNERID { get; set; }
    }
}
