//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.CTMS.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTMS_PRODUCTS
    {
        public string PRODUCTID { get; set; }
        public Nullable<decimal> PRODUCTTYPE { get; set; }
        public string PRODUCTNAME { get; set; }
        public Nullable<decimal> ISFREE { get; set; }
        public Nullable<float> PRODUCTPRICE { get; set; }
        public Nullable<decimal> PRODUCTUNIT { get; set; }
        public Nullable<float> SALEPRICE { get; set; }
        public string PRODUCTREMARK { get; set; }
    }
}
