//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.CTMS.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTMS_SYMPTOMRECORDS
    {
        public string ID { get; set; }
        public string SYMPTOMID { get; set; }
        public string USERID { get; set; }
        public string SYMPTOMLEVEL { get; set; }
        public string DICTSYMLEVELID { get; set; }
        public Nullable<System.DateTime> SYSMPTOMDATE { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.DateTime> EDITDATE { get; set; }
    }
}
