//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.CTMS.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUG_PRODUCTS
    {
        public decimal ID { get; set; }
        public string DRUGBANKID { get; set; }
        public string NDCID { get; set; }
        public string NAME { get; set; }
        public string STRENGTH { get; set; }
        public Nullable<System.DateTime> STARTEDMARKETINGON { get; set; }
    }
}
