//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.CTMS.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUG_CNDRUG
    {
        public string ID { get; set; }
        public string DRUGBANKID { get; set; }
        public string NAME { get; set; }
        public string PINYINCODE { get; set; }
        public string ENNAME { get; set; }
        public string COMMONNAME { get; set; }
        public string TYPENAME { get; set; }
        public string KINDNAME { get; set; }
        public Nullable<decimal> ISPRESCRIPTION { get; set; }
        public Nullable<decimal> ISMEDICALINSURANCE { get; set; }
        public string COMPANY { get; set; }
        public string PACK { get; set; }
        public string DOSAGEFORMS { get; set; }
        public string CONTENT { get; set; }
        public string PRICE { get; set; }
        public string CREATEUSERID { get; set; }
        public string CREATEUSERNAME { get; set; }
        public Nullable<System.DateTime> CREATEDATETIME { get; set; }
        public string EDITUSERID { get; set; }
        public string EDITUSERNAME { get; set; }
        public Nullable<System.DateTime> EDITDATETIME { get; set; }
        public string OWNERID { get; set; }
        public string OWNERNAME { get; set; }
        public decimal ISDELETED { get; set; }
        public string NOTICE { get; set; }
        public string ADVERSE { get; set; }
        public string DOSAGE { get; set; }
        public string DESCRIPTION { get; set; }
        public string INDICATION { get; set; }
        public string CONTRAINDICATION { get; set; }
    }
}
