//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.CTMS.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUG_DRUG
    {
        public decimal ID { get; set; }
        public string DRUGBANKID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public string DIRECTPARENT { get; set; }
        public string SUPERCLASS { get; set; }
        public string INDICATION { get; set; }
        public string PHARMACODYNAMICS { get; set; }
        public string MECHANISMOFACTION { get; set; }
        public string TOXICITY { get; set; }
        public string METABOLISM { get; set; }
        public string ABSORPTION { get; set; }
        public string PROTEINBINDING { get; set; }
    }
}
