//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.CTMS.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class GN_GENEALLELELOCUS
    {
        public string ID { get; set; }
        public string GENEALLELEID { get; set; }
        public string LOCUSTYPE { get; set; }
        public Nullable<decimal> STARTPOSITION { get; set; }
        public Nullable<decimal> ENDPOSITION { get; set; }
        public string STANDARDVALUE { get; set; }
        public string VARIANTVALUE { get; set; }
        public string VARIANTTYPE { get; set; }
        public string VARIANTCATEGORY { get; set; }
        public string VARIANTCODE { get; set; }
        public string CREATEUSERID { get; set; }
        public string CREATEUSERNAME { get; set; }
        public Nullable<System.DateTime> CREATEDATETIME { get; set; }
        public string EDITUSERID { get; set; }
        public string EDITUSERNAME { get; set; }
        public Nullable<System.DateTime> EDITDATETIME { get; set; }
        public string OWNERID { get; set; }
        public string OWNERNAME { get; set; }
        public decimal ISDELETED { get; set; }
        public string HGVSNAME { get; set; }
        public string AMINOACIDEFFECT { get; set; }
        public string VARIANTGUIDELINE { get; set; }
    }
}
