//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.CTMS.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class HPN_SENDVERCODELOG
    {
        public string ID { get; set; }
        public Nullable<System.DateTime> INPUTTIME { get; set; }
        public string MOBILEPHONE { get; set; }
        public string EMAIL { get; set; }
        public string FORMURL { get; set; }
        public string VERCODE { get; set; }
        public Nullable<decimal> STATUS { get; set; }
        public string FORMDATA { get; set; }
        public string RESULT { get; set; }
    }
}
