//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.CTMS.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class HPN_RESULTDESC
    {
        public string ID { get; set; }
        public string TEMPLATENAME { get; set; }
        public string SUBRESULTNAME { get; set; }
        public Nullable<decimal> MINSCORES { get; set; }
        public Nullable<decimal> MAXSCORES { get; set; }
        public string RESULT { get; set; }
        public string RESULTDETAIL { get; set; }
    }
}
