//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.CTMS.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class HPN_TESTRESULT
    {
        public string ID { get; set; }
        public Nullable<System.DateTime> INPUTTIME { get; set; }
        public string TESTNO { get; set; }
        public string OTHERTESTNO { get; set; }
        public string USERID { get; set; }
        public string TEMPLATENAME { get; set; }
        public Nullable<decimal> TESTSTATUS { get; set; }
        public string IP { get; set; }
        public string SCORE { get; set; }
        public string TESTRESULT { get; set; }
        public string RESULTDETAIL { get; set; }
    }
}
