//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.CTMS.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class HPN_TEMPLATEITEMOPTIONS
    {
        public string ID { get; set; }
        public string TEMPLATENAME { get; set; }
        public string TEMPLATEITEMNAME { get; set; }
        public string TEXT { get; set; }
        public string VALUEATTR { get; set; }
        public string NAMEATTR { get; set; }
        public string IDATTR { get; set; }
        public Nullable<decimal> INDEXATTR { get; set; }
    }
}
