//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.CTMS.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_ANNUALINCOME
    {
        public string ANNUALINCOMEID { get; set; }
        public string PERSONID { get; set; }
        public string ANNUALINCOME { get; set; }
        public Nullable<System.DateTime> CREATTIME { get; set; }
        public string CREATBY { get; set; }
        public Nullable<System.DateTime> MODIFYTIME { get; set; }
        public string MODIFYBY { get; set; }
    }
}
