//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.CTMS.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_ATTACHMENT
    {
        public string ATTACHMENTRECORDID { get; set; }
        public string RECORDID { get; set; }
        public string ATTACHMENTID { get; set; }
        public string ATTACHMENTURL { get; set; }
        public string ATTACHMENTPATH { get; set; }
        public string CREATEUSER { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string EDITUSER { get; set; }
        public Nullable<System.DateTime> EDITDATE { get; set; }
    }
}
