//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.CTMS.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_DICTIONARY
    {
        public string DICTIONARYID { get; set; }
        public string FATHERID { get; set; }
        public string DICTIONCATEGORY { get; set; }
        public string DICTIONARYNAME { get; set; }
        public string DICTIONARYVALUE { get; set; }
        public string CREATEUSER { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string UPDATEUSER { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public string DICTIONCATEGORYNAME { get; set; }
        public string REMARK { get; set; }
        public string SYSTEMNAME { get; set; }
        public string SYSTEMCODE { get; set; }
        public Nullable<decimal> ORDERNUMBER { get; set; }
        public string SYSTEMNEED { get; set; }
        public Nullable<decimal> ISDELETED { get; set; }
    }
}
