//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.CTMS.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_DISEASEHISTORY
    {
        public string DISEASEHISTORYID { get; set; }
        public string PERSONID { get; set; }
        public string DISEASENAME { get; set; }
        public string ANNUALINCOME { get; set; }
        public string TREATPROCESS { get; set; }
        public Nullable<System.DateTime> CREATTIME { get; set; }
        public string HOSPITAL { get; set; }
        public string CREATUSER { get; set; }
        public string EDITUSER { get; set; }
        public Nullable<System.DateTime> EDITTIME { get; set; }
        public Nullable<System.DateTime> STARTTIME { get; set; }
        public Nullable<System.DateTime> RECOVERTIME { get; set; }
        public Nullable<System.DateTime> CONFIRMEDTIME { get; set; }
        public string CONFIRMEDAGE { get; set; }
        public string CONFIRMEDADDRESS { get; set; }
        public string CONFIRMEDMODE { get; set; }
        public string CONFIRMEDRELUST { get; set; }
        public string SYMPTOMDESCRIPTION { get; set; }
        public string ISCANCER { get; set; }
        public string CANCERCODE { get; set; }
        public string CANCERNAME { get; set; }
        public string CANCERPOSITION { get; set; }
        public string CELLULATYPE { get; set; }
        public string CLINICALSTAGES { get; set; }
        public string TUMOR { get; set; }
        public string N { get; set; }
        public string M { get; set; }
        public string GENE { get; set; }
        public string ISREAPPEAR { get; set; }
    }
}
