//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.CTMS.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_FILEUPLOAD
    {
        public string FILEUPLOADID { get; set; }
        public string MODELNAME { get; set; }
        public string MODELCODE { get; set; }
        public string FORMID { get; set; }
        public string FILEPAH { get; set; }
        public string FILENAME { get; set; }
        public Nullable<System.DateTime> CREATTIME { get; set; }
        public string CREATBY { get; set; }
        public Nullable<System.DateTime> MODIFYTIME { get; set; }
        public string MODIFYBY { get; set; }
        public string REMARK { get; set; }
    }
}
