//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.CTMS.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_FD_RELATION
    {
        public string ID { get; set; }
        public string CODE { get; set; }
        public string TEXT { get; set; }
        public Nullable<decimal> RELATIONVALUE { get; set; }
        public string SIDE { get; set; }
        public string GENERATE { get; set; }
        public Nullable<decimal> REQUIRD { get; set; }
        public Nullable<decimal> APPLY { get; set; }
        public Nullable<decimal> SORT { get; set; }
        public Nullable<decimal> SEX { get; set; }
    }
}
