//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.CTMS.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_IMAGEEXAMINATION
    {
        public string IMAGEEXAMID { get; set; }
        public string HISTORYID { get; set; }
        public string CHECKTYPE { get; set; }
        public Nullable<System.DateTime> CHECKTIME { get; set; }
        public string DEPARTMENT { get; set; }
        public string CHECKPOSITION { get; set; }
        public string REPORTCONTENT { get; set; }
        public Nullable<System.DateTime> REPORTTIME { get; set; }
        public string REPORTDOCTOR { get; set; }
        public string AUDITDOCTOR { get; set; }
        public string REMARK { get; set; }
    }
}
