//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.CTMS.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_LABORATORYTESTITEM
    {
        public string TESTITEMID { get; set; }
        public string ORDERNUMBER { get; set; }
        public string ITEMNAME { get; set; }
        public string ITEMNAMEEN { get; set; }
        public string ITEMVALUE { get; set; }
        public string RESLUT { get; set; }
        public string UOM { get; set; }
        public string NORMALVALUE { get; set; }
        public string REFERENCEVALUE { get; set; }
        public string LABRESULTID { get; set; }
        public string ITEMID { get; set; }
        public string INSPECTEDMEANS { get; set; }
        public string ITEMUNITID { get; set; }
    }
}
