//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.CTMS.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_LABTESTRECORD
    {
        public decimal RECORDID { get; set; }
        public Nullable<System.DateTime> RECORDDATE { get; set; }
        public string HOSPITAL { get; set; }
        public string LABDOCTOR { get; set; }
        public Nullable<decimal> ITEMID { get; set; }
        public string REPORT { get; set; }
        public string ATTACHMENTS { get; set; }
        public string ITEMNAME { get; set; }
        public string ITEMNO { get; set; }
        public string RECORDNO { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public string UPDATEBY { get; set; }
        public Nullable<decimal> STATUS { get; set; }
    }
}
