//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.CTMS.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_LABORATORYRESULT
    {
        public string LABRESULTID { get; set; }
        public string HISTORYID { get; set; }
        public Nullable<System.DateTime> DIAGNOSISTIME { get; set; }
        public string DIAGNOSIS { get; set; }
        public string HOSPITAL { get; set; }
        public string DIAGNOSISREPORT { get; set; }
        public string CI { get; set; }
        public string MEDICALHISATTACHMENT { get; set; }
        public string LABMODELID { get; set; }
        public string LABTABELNAME { get; set; }
        public string TESTSTANDARD { get; set; }
    }
}
