//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.CTMS.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_PERSONHEALTHHISTORY
    {
        public decimal HISTORYID { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public Nullable<decimal> DISEASEID { get; set; }
        public string DISEASENO { get; set; }
        public string DISEASENAME { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public string UPDATEBY { get; set; }
        public Nullable<decimal> STATUS { get; set; }
        public Nullable<decimal> PERSONID { get; set; }
        public string SYMPTOM { get; set; }
        public string ATTACHMENTS { get; set; }
        public string TREATMENT { get; set; }
        public string RESULT { get; set; }
    }
}
