//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.CTMS.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_PERSONINFO
    {
        public decimal PERSONID { get; set; }
        public string PERSONNO { get; set; }
        public string NAME { get; set; }
        public string GENDER { get; set; }
        public string BIRTHDATE { get; set; }
        public string COUNTRY { get; set; }
        public string NATIONALITY { get; set; }
        public string MARRIAGESTATUS { get; set; }
        public string IDTYPE { get; set; }
        public string IDNUMBER { get; set; }
        public string PHONE { get; set; }
        public string CONTACTNAME { get; set; }
        public string CONTACTPHONE { get; set; }
        public string EMAILADDRESS { get; set; }
        public string CENSUSREGISTERFLAG { get; set; }
        public string CENSUSADDRESSCODE { get; set; }
        public string CENSUSADDRESSNAME { get; set; }
        public string CENSUSPOSTCODE { get; set; }
        public string CURRENTADDRESSCODE { get; set; }
        public string CURRENTADDRESSNAME { get; set; }
        public string CURRENTPOSTCODE { get; set; }
        public string COMPANY { get; set; }
        public string HIREDATE { get; set; }
        public string OCCUPATIONCLASS { get; set; }
        public string EDUCATIONLEVEL { get; set; }
        public string INSURANCETYPE { get; set; }
        public string INSURANCETYPENAME { get; set; }
        public string PAYMETHOD { get; set; }
        public string ABOTYPE { get; set; }
        public string RHTYPE { get; set; }
        public string ALLERGYHISTORY { get; set; }
        public string RISKFACTORS { get; set; }
        public string DISABILITYSTATUS { get; set; }
        public string COMMUNITY { get; set; }
        public string COMMUNITYCONTACT { get; set; }
        public string COMMUNITYCONTACTPHONE { get; set; }
        public string RESPONSIBLEORGANIZATION { get; set; }
        public string RESPONSIBLEORGANIZATIONID { get; set; }
        public string RESPONSIBLEDOCTOR { get; set; }
        public string RESPONSIBLEDOCTORPHONE { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public string UPDATEBY { get; set; }
        public decimal STATUS { get; set; }
        public Nullable<System.DateTime> ARCHIVEDATE { get; set; }
        public string REMARK { get; set; }
        public string BLOODTYPE { get; set; }
        public string RECORDNO { get; set; }
    }
}
