//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.CTMS.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_SEEDOCTORHISTORY
    {
        public string HISTORYID { get; set; }
        public string PERSONID { get; set; }
        public Nullable<System.DateTime> DIAGNOSISTIME { get; set; }
        public string DIAGNOSIS { get; set; }
        public string ICD10 { get; set; }
        public string HOSPITAL { get; set; }
        public string DIAGNOSISREPORT { get; set; }
        public string MEDICALHISATTACHMENT { get; set; }
        public string MAINDISEASE { get; set; }
        public string PERSONHISTORY { get; set; }
        public string OBSTETRICALHISTORY { get; set; }
        public string MENSTRUALHISTORY { get; set; }
        public string PHYSICALEXAM { get; set; }
        public string SPECIALISTCASE { get; set; }
        public string AUXILIARYEXAM { get; set; }
        public string HISTOLOGICALLY { get; set; }
        public string MOLECULARPATHOLOGIC { get; set; }
        public decimal DISEASETYPE { get; set; }
        public decimal ISRELAPSE { get; set; }
        public string T { get; set; }
        public string M { get; set; }
        public string N { get; set; }
        public string POSITION { get; set; }
        public string STAGE { get; set; }
        public string CYTOTYPE { get; set; }
        public string GENOTYPING { get; set; }
        public string TRANSFER { get; set; }
    }
}
