//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.CTMS.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_SCORE
    {
        public string SCOREID { get; set; }
        public string PERSONID { get; set; }
        public string TABLETYPE { get; set; }
        public string TEMPLATETITLE { get; set; }
        public Nullable<decimal> TOTALSCORE { get; set; }
        public string GRADE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string USERID { get; set; }
        public string TEMPLATEID { get; set; }
        public string TEMPLATEDESCRIPTION { get; set; }
        public string TEMPLATELABEL { get; set; }
        public Nullable<decimal> SHOWGRADE { get; set; }
        public Nullable<decimal> ISSHOWRESULT { get; set; }
        public string QUESTIONSJSON { get; set; }
        public string ANSWERSJSON { get; set; }
    }
}
