//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.CTMS.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_SCORETEMPLATE
    {
        public string TEMPLATEID { get; set; }
        public string TEMPLATETITLE { get; set; }
        public string TEMPLATEDESCRIPTION { get; set; }
        public string TEMPLATELABEL { get; set; }
        public Nullable<decimal> SHOWGRADE { get; set; }
        public Nullable<decimal> ISSHOWRESULT { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> MODIFYTIME { get; set; }
        public string MODIFYBY { get; set; }
        public string QUESTIONSJSON { get; set; }
        public string ANSWERSJSON { get; set; }
    }
}
