//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.CTMS.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_SEEDOCHISICD
    {
        public string INFOID { get; set; }
        public string HISTORYID { get; set; }
        public string ICDCODE { get; set; }
        public string ICDNAME { get; set; }
        public string DETAILS { get; set; }
        public decimal ISMAIN { get; set; }
    }
}
