//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.CTMS.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_TEMPLATEITEMUNIT
    {
        public string ITEMUNITID { get; set; }
        public string ITEMID { get; set; }
        public string UNITNAME { get; set; }
        public string UNITDESC { get; set; }
    }
}
